# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='phoneNo',
        ),
    ]
