# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.FloatField()),
                ('task_name', models.FloatField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('Karur', django.db.models.manager.Manager()),
            ],
        ),
    ]
