# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blogs_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='actual_date_completion',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 28, 13, 49, 32, 711457)),
        ),
        migrations.AddField(
            model_name='blogs',
            name='actual_effort',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='actual_start_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 13, 49, 32, 711457)),
        ),
        migrations.AddField(
            model_name='blogs',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 13, 49, 32, 711457)),
        ),
        migrations.AddField(
            model_name='blogs',
            name='effort_estimated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default='1', max_length=6),
        ),
        migrations.AddField(
            model_name='blogs',
            name='reason',
            field=models.TextField(default='Significant achievement of your resource.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='resource_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blogs',
            name='resource_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('1', 'In Progress'), ('2', 'Completed'), ('3', 'Hold')], default='1', max_length=6),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='task_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
