# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180428_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='actual_start_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 20, 10, 23, 798004)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 20, 10, 23, 798004)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=6),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('HOLD', 'Hold')], default='IN PROGRESS', max_length=6),
        ),
    ]
