# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180428_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='actual_start_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 29, 10, 48, 9, 234190)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2018, 4, 29, 10, 48, 9, 234190)),
        ),
    ]
