# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-27 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180526_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='actual_start_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 12, 50, 38, 898355)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 12, 50, 38, 898355)),
        ),
    ]
